#!/bin/sh
# Run from OPENFOAM top-level directory only
cd "${0%/*}" || exit

cd ../rigidBodyMeshMotion/
wclean
wmake > log.wmake

cd rigidBodyDynamics/
wclean
wmake > log.wmake
#------------------------------------------------------------------------------
